# Generated by Django 5.0 on 2024-03-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTNTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('bundle_volume', models.FloatField(default=0)),
                ('status', models.CharField(default='Undelivered', max_length=200)),
                ('batch_id', models.CharField(default='Unknown', max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('firebase_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
